### ISSUE TITLE
Follow Url Redirects

### ISSUE THREAD

**Issue by Mutale85** [sznowicki/uptime-check#9]
Hello, Thanks you making this awesome library.
I'm new to node js and I landed on your module, am trying to integrate it into my software.
How do i follow the url redirect and get the original httpCode?

```
var check = require("uptime-check")

var result = check({
  url: 'https://example.com',
  keyword: 'example',
  redirectsLimit: 2
})

.then(result => {
    
    console.log(result.httpCode)
  })
  .catch((err) => {
    /*
    err = '{Error} unexpected error.';
    */
  });

```
Lets say, the https://example.com has redirected to https://example-new.net
am getting code 503 for some websites.

Will be glad to hear from you.

**Comment by sznowicki** [comment]
Hello there

Sorry for not responding earlier. This issue got buried in my GitHub inbox.

At the moment this library doesn't provide original httpCode from a redirection. If there was a redirection it's must be some 300 code, otherwise it would not be considered as such.

The purpose of this library is to answer the question: is this url up or down. If you need more verbose check I suggest using a different one, or even just `http` or `https` native node libraries.

Cheers!
